### ISSUE TITLE
Padrão de nomencratura

### ISSUE THREAD

**Issue by LuizinhoF** [andrelsmelo/exerc-typescript#1]
https://github.com/andrelsmelo/exerc-typescript/blob/0eea1370cdcd89a1ff4ca44e1120d3cd614bc007/src/app.ts#L11

Ví que você tem váriaveis com nomes em inglês e outras em português, é muito comum matermos todos os nomes em inglês.
Faz parte da Cultura WebDev

**Comment by andrelsmelo** [comment]
Ajustado Nomenclaturas
